USE [master]
GO
/****** Object:  Database [Airmaster_ShippingDb]    Script Date: 10-07-2026 15:21:24 ******/
CREATE DATABASE [Airmaster_ShippingDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Airmaster_ShippingDb', FILENAME = N'C:\Users\amitk\Airmaster_ShippingDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Airmaster_ShippingDb_log', FILENAME = N'C:\Users\amitk\Airmaster_ShippingDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Airmaster_ShippingDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Airmaster_ShippingDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET  MULTI_USER 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Airmaster_ShippingDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [Airmaster_ShippingDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
USE [Airmaster_ShippingDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 10-07-2026 15:21:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Shipments]    Script Date: 10-07-2026 15:21:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Shipments](
	[Id] [uniqueidentifier] NOT NULL,
	[OrderId] [uniqueidentifier] NOT NULL,
	[UserId] [uniqueidentifier] NOT NULL,
	[TrackingNumber] [nvarchar](50) NOT NULL,
	[Carrier] [nvarchar](max) NOT NULL,
	[ShippingStatus] [nvarchar](max) NOT NULL,
	[CreatedAtUtc] [datetime2](7) NOT NULL,
 CONSTRAINT [PK_Shipments] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Index [IX_Shipments_OrderId]    Script Date: 10-07-2026 15:21:24 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Shipments_OrderId] ON [dbo].[Shipments]
(
	[OrderId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [Airmaster_ShippingDb] SET  READ_WRITE 
GO
